language: node_js
before_install:
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar jxf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - export PATH=$PATH:$PWD/phantomjs-2.1.1-linux-x86_64/bin
  - npm install -g casperjs
  - npm install -g mocha
services:
  - mongodb
